### ISSUE TITLE
What is the license on this package? 

### ISSUE THREAD

**Issue by TrentBrick** [rfeinman/pytorch-lasso#4]
Thanks!

Trenton

**Comment by rfeinman** [comment]
Just added a license with [6c2023d](https://github.com/rfeinman/pytorch-lasso/commit/6c2023d2511d475ef781bec63f81288fd8f8cd23). Forgot it initially. Thanks!

**Comment by TrentBrick** [comment]
Awesome, and glad to see it is MIT, thanks!
